// File generated by FlutterFire CLI.
// Based on the google-services.json for project: prepora-c2d23

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIeAkGcbZCZPBB7n-2rmGx6f6yU2m58dY',
    authDomain: 'prepora-c2d23.firebaseapp.com',
    projectId: 'prepora-c2d23',
    storageBucket: 'prepora-c2d23.firebasestorage.app',
    messagingSenderId: '546702209629',
    appId: '1:546702209629:web:49233391c3654113abd3b4',
    measurementId: 'G-4KD9MKZ844',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT6_9BBHSMGB85b3fjlQEWDqCg35jLrFs',
    appId: '1:546702209629:android:15125a9bd6433df9abd3b4',
    messagingSenderId: '546702209629',
    projectId: 'prepora-c2d23',
    storageBucket: 'prepora-c2d23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbmF51WfQwba3jjfB_APa1sdscPkrEjM4',
    appId: '1:546702209629:ios:eb87a92a8ea52569abd3b4',
    messagingSenderId: '546702209629',
    projectId: 'prepora-c2d23',
    storageBucket: 'prepora-c2d23.firebasestorage.app',
    iosBundleId: 'com.example.prepora',
  );
}
